package com.example.bikeredlights.data.repository

import com.example.bikeredlights.data.local.dao.StopDao
import com.example.bikeredlights.data.local.entity.StopEntity
import com.example.bikeredlights.domain.model.Stop
import io.mockk.*
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Before
import org.junit.Test

/**
 * Unit tests for StopRepositoryImpl (Feature 009, Phase 2, Task T014).
 *
 * Test Strategy:
 * - Mock StopDao to isolate repository logic from database
 * - Verify correct entity/model mapping between layers
 * - Verify DAO methods are called with correct parameters
 * - Test all repository methods defined in StopRepository interface
 *
 * Coverage:
 * - insertStop: Domain model → Entity mapping + DAO delegation
 * - updateStopEnd: DAO parameter forwarding
 * - getStopsByRideId: Entity list → Domain model list mapping
 * - getStopCountByRideId: Flow<Int> delegation (no mapping)
 * - getUnclusteredStops: Entity list → Domain model list mapping
 * - updateStopCluster: DAO parameter forwarding
 * - getStopById: Entity → Domain model mapping (with null handling)
 * - deleteStopsByRideId: DAO delegation
 *
 * Mocking Framework: MockK (Kotlin-first, better coroutine support than Mockito)
 *
 * Test Patterns:
 * - Use runTest { } for suspending functions
 * - Use coEvery/coVerify for suspend mocking/verification
 * - Use every/verify for regular function mocking/verification
 * - Clear mocks after each test to prevent state leakage
 */
class StopRepositoryImplTest {

    // Mock DAO (data layer dependency)
    private lateinit var mockStopDao: StopDao

    // System under test
    private lateinit var repository: StopRepositoryImpl

    // Test data fixtures
    private val testRideId = 1L
    private val testStopId = 42L
    private val testLatitude = 46.2044
    private val testLongitude = 6.1432
    private val testStartTime = 1000000L
    private val testEndTime = 1020000L
    private val testDurationSeconds = 20

    @Before
    fun setup() {
        mockStopDao = mockk()
        repository = StopRepositoryImpl(mockStopDao)
    }

    @After
    fun teardown() {
        clearAllMocks()
    }

    // ============================================================================
    // INSERT TESTS (Domain Model → Entity Mapping + DAO Delegation)
    // ============================================================================

    @Test
    fun `insertStop maps domain model to entity and delegates to DAO`() = runTest {
        // Given: Domain model for active stop (no endTimestamp/duration)
        val domainStop = Stop(
            id = 0L,  // Unsaved (will be generated by database)
            rideId = testRideId,
            stopNumber = 1,
            latitude = testLatitude,
            longitude = testLongitude,
            startTimestamp = testStartTime,
            endTimestamp = null,
            durationSeconds = null,
            clusterId = null
        )

        val expectedEntity = StopEntity(
            id = 0L,
            rideId = testRideId,
            stopNumber = 1,
            latitude = testLatitude,
            longitude = testLongitude,
            startTimestamp = testStartTime,
            endTimestamp = null,
            durationSeconds = null,
            clusterId = null
        )

        coEvery { mockStopDao.insertStop(expectedEntity) } returns testStopId

        // When: Insert stop via repository
        val result = repository.insertStop(domainStop)

        // Then: Returns DAO-generated ID
        assertEquals(testStopId, result)

        // Verify DAO called with correctly mapped entity
        coVerify(exactly = 1) { mockStopDao.insertStop(expectedEntity) }
    }

    @Test
    fun `insertStop preserves all domain model fields in entity mapping`() = runTest {
        // Given: Domain model with all fields populated (ended stop with cluster)
        val domainStop = Stop(
            id = 5L,  // Existing ID (for update scenarios)
            rideId = testRideId,
            stopNumber = 3,
            latitude = testLatitude,
            longitude = testLongitude,
            startTimestamp = testStartTime,
            endTimestamp = testEndTime,
            durationSeconds = testDurationSeconds,
            clusterId = 99L
        )

        val expectedEntity = StopEntity(
            id = 5L,
            rideId = testRideId,
            stopNumber = 3,
            latitude = testLatitude,
            longitude = testLongitude,
            startTimestamp = testStartTime,
            endTimestamp = testEndTime,
            durationSeconds = testDurationSeconds,
            clusterId = 99L
        )

        coEvery { mockStopDao.insertStop(expectedEntity) } returns testStopId

        // When: Insert stop
        repository.insertStop(domainStop)

        // Then: All fields correctly mapped
        coVerify(exactly = 1) { mockStopDao.insertStop(expectedEntity) }
    }

    // ============================================================================
    // UPDATE TESTS (Parameter Forwarding to DAO)
    // ============================================================================

    @Test
    fun `updateStopEnd forwards parameters to DAO correctly`() = runTest {
        // Given: Stop end parameters
        val stopId = testStopId
        val endTimestamp = testEndTime
        val durationSeconds = testDurationSeconds

        coEvery { mockStopDao.updateStopEnd(stopId, endTimestamp, durationSeconds) } just Runs

        // When: Update stop end
        repository.updateStopEnd(stopId, endTimestamp, durationSeconds)

        // Then: DAO called with exact parameters
        coVerify(exactly = 1) {
            mockStopDao.updateStopEnd(stopId, endTimestamp, durationSeconds)
        }
    }

    @Test
    fun `updateStopCluster forwards parameters to DAO correctly`() = runTest {
        // Given: Cluster assignment parameters
        val stopId = testStopId
        val clusterId = 77L

        coEvery { mockStopDao.updateStopCluster(stopId, clusterId) } just Runs

        // When: Update cluster
        repository.updateStopCluster(stopId, clusterId)

        // Then: DAO called with exact parameters
        coVerify(exactly = 1) {
            mockStopDao.updateStopCluster(stopId, clusterId)
        }
    }

    // ============================================================================
    // QUERY TESTS (Entity List → Domain Model List Mapping)
    // ============================================================================

    @Test
    fun `getStopsByRideId maps entities to domain models correctly`() = runTest {
        // Given: DAO returns list of entities
        val entities = listOf(
            StopEntity(
                id = 1L,
                rideId = testRideId,
                stopNumber = 1,
                latitude = testLatitude,
                longitude = testLongitude,
                startTimestamp = testStartTime,
                endTimestamp = testEndTime,
                durationSeconds = testDurationSeconds,
                clusterId = null
            ),
            StopEntity(
                id = 2L,
                rideId = testRideId,
                stopNumber = 2,
                latitude = 46.2050,
                longitude = 6.1440,
                startTimestamp = testStartTime + 30000,
                endTimestamp = null,
                durationSeconds = null,
                clusterId = null
            )
        )

        coEvery { mockStopDao.getStopsByRideId(testRideId) } returns entities

        // When: Get stops by ride ID
        val result = repository.getStopsByRideId(testRideId)

        // Then: Entities correctly mapped to domain models
        assertEquals(2, result.size)

        // Stop 1 (ended)
        with(result[0]) {
            assertEquals(1L, id)
            assertEquals(testRideId, rideId)
            assertEquals(1, stopNumber)
            assertEquals(testLatitude, latitude, 0.0001)
            assertEquals(testLongitude, longitude, 0.0001)
            assertEquals(testStartTime, startTimestamp)
            assertEquals(testEndTime, endTimestamp)
            assertEquals(testDurationSeconds, durationSeconds)
            assertNull(clusterId)
        }

        // Stop 2 (active)
        with(result[1]) {
            assertEquals(2L, id)
            assertEquals(testRideId, rideId)
            assertEquals(2, stopNumber)
            assertNull(endTimestamp)
            assertNull(durationSeconds)
        }

        coVerify(exactly = 1) { mockStopDao.getStopsByRideId(testRideId) }
    }

    @Test
    fun `getStopsByRideId with empty list returns empty domain list`() = runTest {
        // Given: DAO returns empty list
        coEvery { mockStopDao.getStopsByRideId(testRideId) } returns emptyList()

        // When: Get stops
        val result = repository.getStopsByRideId(testRideId)

        // Then: Empty list returned
        assertEquals(0, result.size)
        coVerify(exactly = 1) { mockStopDao.getStopsByRideId(testRideId) }
    }

    @Test
    fun `getUnclusteredStops maps entities to domain models correctly`() = runTest {
        // Given: DAO returns unclustered entities
        val entities = listOf(
            StopEntity(
                id = 10L,
                rideId = testRideId,
                stopNumber = 1,
                latitude = testLatitude,
                longitude = testLongitude,
                startTimestamp = testStartTime,
                endTimestamp = testEndTime,
                durationSeconds = testDurationSeconds,
                clusterId = null  // Unclustered
            ),
            StopEntity(
                id = 11L,
                rideId = testRideId + 1,
                stopNumber = 2,
                latitude = 46.2050,
                longitude = 6.1440,
                startTimestamp = testStartTime + 1000,
                endTimestamp = testEndTime + 1000,
                durationSeconds = testDurationSeconds,
                clusterId = null  // Unclustered
            )
        )

        coEvery { mockStopDao.getUnclusteredStops() } returns entities

        // When: Get unclustered stops
        val result = repository.getUnclusteredStops()

        // Then: Entities correctly mapped
        assertEquals(2, result.size)
        assertEquals(10L, result[0].id)
        assertEquals(11L, result[1].id)
        assertNull(result[0].clusterId)
        assertNull(result[1].clusterId)

        coVerify(exactly = 1) { mockStopDao.getUnclusteredStops() }
    }

    @Test
    fun `getUnclusteredStops with empty list returns empty domain list`() = runTest {
        // Given: DAO returns empty list (all stops clustered)
        coEvery { mockStopDao.getUnclusteredStops() } returns emptyList()

        // When: Get unclustered stops
        val result = repository.getUnclusteredStops()

        // Then: Empty list returned
        assertEquals(0, result.size)
        coVerify(exactly = 1) { mockStopDao.getUnclusteredStops() }
    }

    // ============================================================================
    // SINGLE ENTITY QUERY TESTS (Entity → Domain Model Mapping with Null Handling)
    // ============================================================================

    @Test
    fun `getStopById maps entity to domain model correctly`() = runTest {
        // Given: DAO returns entity
        val entity = StopEntity(
            id = testStopId,
            rideId = testRideId,
            stopNumber = 1,
            latitude = testLatitude,
            longitude = testLongitude,
            startTimestamp = testStartTime,
            endTimestamp = testEndTime,
            durationSeconds = testDurationSeconds,
            clusterId = 55L
        )

        coEvery { mockStopDao.getStopById(testStopId) } returns entity

        // When: Get stop by ID
        val result = repository.getStopById(testStopId)

        // Then: Entity correctly mapped to domain model
        assertEquals(testStopId, result?.id)
        assertEquals(testRideId, result?.rideId)
        assertEquals(1, result?.stopNumber)
        assertEquals(testLatitude, result?.latitude)
        assertEquals(testLongitude, result?.longitude)
        assertEquals(testStartTime, result?.startTimestamp)
        assertEquals(testEndTime, result?.endTimestamp)
        assertEquals(testDurationSeconds, result?.durationSeconds)
        assertEquals(55L, result?.clusterId)

        coVerify(exactly = 1) { mockStopDao.getStopById(testStopId) }
    }

    @Test
    fun `getStopById with non-existent ID returns null`() = runTest {
        // Given: DAO returns null
        coEvery { mockStopDao.getStopById(testStopId) } returns null

        // When: Get stop by ID
        val result = repository.getStopById(testStopId)

        // Then: Null returned
        assertNull(result)
        coVerify(exactly = 1) { mockStopDao.getStopById(testStopId) }
    }

    // ============================================================================
    // FLOW TESTS (No Mapping - Flow<Int> is Technology-Agnostic)
    // ============================================================================

    @Test
    fun `getStopCountByRideId returns DAO Flow directly`() = runTest {
        // Given: DAO returns Flow
        val expectedCount = 5
        val flow = flowOf(expectedCount)
        every { mockStopDao.getStopCountByRideId(testRideId) } returns flow

        // When: Get stop count Flow
        val result = repository.getStopCountByRideId(testRideId)
        val count = result.first()

        // Then: Flow value matches DAO
        assertEquals(expectedCount, count)
        verify(exactly = 1) { mockStopDao.getStopCountByRideId(testRideId) }
    }

    @Test
    fun `getStopCountByRideId with zero stops returns zero`() = runTest {
        // Given: DAO returns zero count
        val flow = flowOf(0)
        every { mockStopDao.getStopCountByRideId(testRideId) } returns flow

        // When: Get stop count
        val result = repository.getStopCountByRideId(testRideId)
        val count = result.first()

        // Then: Zero returned
        assertEquals(0, count)
        verify(exactly = 1) { mockStopDao.getStopCountByRideId(testRideId) }
    }

    // ============================================================================
    // DELETE TESTS (DAO Delegation)
    // ============================================================================

    @Test
    fun `deleteStopsByRideId delegates to DAO`() = runTest {
        // Given: DAO delete succeeds
        coEvery { mockStopDao.deleteStopsByRideId(testRideId) } just Runs

        // When: Delete stops
        repository.deleteStopsByRideId(testRideId)

        // Then: DAO called with correct rideId
        coVerify(exactly = 1) { mockStopDao.deleteStopsByRideId(testRideId) }
    }

    // ============================================================================
    // EDGE CASE TESTS (Boundary Conditions)
    // ============================================================================

    @Test
    fun `insertStop with GPS boundary values maps correctly`() = runTest {
        // Given: Stop at GPS boundaries
        val domainStop = Stop(
            id = 0L,
            rideId = testRideId,
            stopNumber = 1,
            latitude = 90.0,  // Max latitude
            longitude = 180.0,  // Max longitude
            startTimestamp = testStartTime,
            endTimestamp = null,
            durationSeconds = null,
            clusterId = null
        )

        val expectedEntity = StopEntity(
            id = 0L,
            rideId = testRideId,
            stopNumber = 1,
            latitude = 90.0,
            longitude = 180.0,
            startTimestamp = testStartTime,
            endTimestamp = null,
            durationSeconds = null,
            clusterId = null
        )

        coEvery { mockStopDao.insertStop(expectedEntity) } returns testStopId

        // When: Insert boundary stop
        repository.insertStop(domainStop)

        // Then: Boundary values preserved
        coVerify(exactly = 1) { mockStopDao.insertStop(expectedEntity) }
    }

    @Test
    fun `getStopsByRideId with large list maps all entities`() = runTest {
        // Given: DAO returns 100 entities
        val entities = (1..100).map { i ->
            StopEntity(
                id = i.toLong(),
                rideId = testRideId,
                stopNumber = i,
                latitude = testLatitude,
                longitude = testLongitude,
                startTimestamp = testStartTime + (i * 1000L),
                endTimestamp = null,
                durationSeconds = null,
                clusterId = null
            )
        }

        coEvery { mockStopDao.getStopsByRideId(testRideId) } returns entities

        // When: Get stops
        val result = repository.getStopsByRideId(testRideId)

        // Then: All 100 entities mapped
        assertEquals(100, result.size)
        assertEquals(1L, result[0].id)
        assertEquals(100L, result[99].id)
        coVerify(exactly = 1) { mockStopDao.getStopsByRideId(testRideId) }
    }

    @Test
    fun `updateStopEnd with zero duration forwards correctly`() = runTest {
        // Given: Stop ended immediately (0 seconds duration)
        val stopId = testStopId
        val endTimestamp = testStartTime  // Same as start
        val durationSeconds = 0

        coEvery { mockStopDao.updateStopEnd(stopId, endTimestamp, durationSeconds) } just Runs

        // When: Update with zero duration
        repository.updateStopEnd(stopId, endTimestamp, durationSeconds)

        // Then: DAO called with zero duration
        coVerify(exactly = 1) {
            mockStopDao.updateStopEnd(stopId, endTimestamp, 0)
        }
    }

    @Test
    fun `updateStopEnd with very large duration forwards correctly`() = runTest {
        // Given: Stop with long duration (1 hour = 3600 seconds)
        val stopId = testStopId
        val endTimestamp = testStartTime + 3_600_000L  // +1 hour
        val durationSeconds = 3600

        coEvery { mockStopDao.updateStopEnd(stopId, endTimestamp, durationSeconds) } just Runs

        // When: Update with large duration
        repository.updateStopEnd(stopId, endTimestamp, durationSeconds)

        // Then: DAO called with large duration
        coVerify(exactly = 1) {
            mockStopDao.updateStopEnd(stopId, endTimestamp, 3600)
        }
    }
}
