package com.example.bikeredlights.domain.model

/**
 * Domain model representing a cycling ride session.
 *
 * **Design Principles**:
 * - Immutable data class
 * - Domain layer (independent of Room entities)
 * - All measurements in SI base units
 * - Timestamps in Unix epoch milliseconds
 *
 * **Time Tracking Strategy**:
 * - **elapsedDuration**: Total wall-clock time (end - start)
 * - **movingDuration**: Time spent moving (speed > threshold)
 * - **manualPausedDuration**: Time user manually paused
 * - **autoPausedDuration**: Time auto-paused (speed too low)
 *
 * **Relationship**:
 * - Formula: elapsedDuration = movingDuration + manualPausedDuration + autoPausedDuration
 * - Moving time excludes all pauses
 * - Average speed calculated from moving time only
 *
 * @property id Unique identifier (auto-generated by database)
 * @property name Human-readable ride name (default: "Ride on MMM d, yyyy")
 * @property startTime Ride start time in Unix epoch milliseconds
 * @property endTime Ride end time in Unix epoch milliseconds (null if incomplete)
 * @property elapsedDurationMillis Total elapsed time in milliseconds
 * @property movingDurationMillis Time spent moving in milliseconds
 * @property manualPausedDurationMillis Time manually paused in milliseconds
 * @property autoPausedDurationMillis Time auto-paused in milliseconds
 * @property distanceMeters Total distance traveled in meters
 * @property avgSpeedMetersPerSec Average speed in meters per second (moving time only)
 * @property maxSpeedMetersPerSec Maximum speed reached in meters per second
 */
data class Ride(
    val id: Long = 0,
    val name: String,
    val startTime: Long,
    val endTime: Long? = null,
    val elapsedDurationMillis: Long = 0,
    val movingDurationMillis: Long = 0,
    val manualPausedDurationMillis: Long = 0,
    val autoPausedDurationMillis: Long = 0,
    val distanceMeters: Double = 0.0,
    val avgSpeedMetersPerSec: Double = 0.0,
    val maxSpeedMetersPerSec: Double = 0.0
) {
    /**
     * Check if ride is complete (has endTime).
     */
    val isComplete: Boolean
        get() = endTime != null

    /**
     * Check if ride is incomplete (no endTime).
     */
    val isIncomplete: Boolean
        get() = endTime == null
}
