package com.example.bikeredlights.domain.model

/**
 * Domain model representing a GPS track point captured during a ride.
 *
 * **Design Principles**:
 * - Immutable data class
 * - Domain layer (independent of Room entities)
 * - All measurements in SI base units
 * - Timestamps in Unix epoch milliseconds
 *
 * **GPS Data**:
 * - Latitude/Longitude in decimal degrees
 * - Speed from GPS provider (meters per second)
 * - Accuracy in meters (horizontal accuracy radius)
 *
 * **Pause State**:
 * - **isManuallyPaused**: User pressed pause button
 * - **isAutoPaused**: Speed below threshold (auto-pause feature)
 * - Both can be false (actively recording)
 * - Cannot both be true (manual pause takes priority)
 *
 * **Use Cases**:
 * - Distance calculation (Haversine formula between consecutive points)
 * - Speed tracking over time
 * - Route reconstruction on map
 * - Moving time calculation (exclude paused points)
 *
 * @property id Unique identifier (auto-generated by database)
 * @property rideId Foreign key to parent Ride
 * @property timestamp Point capture time in Unix epoch milliseconds
 * @property latitude Latitude in decimal degrees (-90 to +90)
 * @property longitude Longitude in decimal degrees (-180 to +180)
 * @property speedMetersPerSec Speed at this point in meters per second
 * @property accuracy Horizontal accuracy in meters (smaller = more accurate)
 * @property isManuallyPaused True if user manually paused at this point
 * @property isAutoPaused True if auto-paused (speed below threshold) at this point
 */
data class TrackPoint(
    val id: Long = 0,
    val rideId: Long,
    val timestamp: Long,
    val latitude: Double,
    val longitude: Double,
    val speedMetersPerSec: Double,
    val accuracy: Float,
    val isManuallyPaused: Boolean = false,
    val isAutoPaused: Boolean = false
) {
    /**
     * Check if this point represents active movement (not paused).
     */
    val isMoving: Boolean
        get() = !isManuallyPaused && !isAutoPaused
}
